import re

with open("C:/Users/Sebastian Lopez/Desktop/MULTIFACTU-Supabase/client/src/pages/TemplatesEditor.tsx", "r", encoding="utf-8") as f:
    content = f.read()

# Fix style attributes split across lines
content = content.replace("<p style={\n{", "<p style={{")
content = content.replace('<legend style={\n{', '<legend style={{')
content = content.replace('<div style={\n{', '<div style={{')
content = content.replace('<button style={\n{', '<button style={{')
content = content.replace('<input style={\n{', '<input style={{')
content = content.replace('<textarea style={\n{', '<textarea style={{')
content = content.replace('<select style={\n{', '<select style={{')
content = content.replace('<fieldset style={\n{', '<fieldset style={{')
content = content.replace('<legend style={\n{', '<legend style={{')
content = content.replace('<p style={\n{', '<p style={{')
content = content.replace('<label style={\n{', '<label style={{')
content = content.replace('<button style={\n{', '<button style={{')
content = content.replace('<input style={\n{', '<input style={{')
content = content.replace('<textarea style={\n{', '<textarea style={{')
content = content.replace('<select style={\n{', '<select style={{')
content = content.replace('<fieldset style={\n{', '<fieldset style={{')
content = content.replace('<legend style={\n{', '<legend style={{')
content = content.replace('<p style={\n{', '<p style={{')
content = content.replace('<label style={\n{', '<label style={{')
content = content.replace('<button style={\n{', '<button style={{')
content = content.replace('<input style={\n{', '<input style={{')
content = content.replace('<textarea style={\n{', '<textarea style={{')
content = content.replace('<select style={\n{', '<select style={{')
content = content.replace('<fieldset style={\n{', '<fieldset style={{')
content = content.replace('<legend style={\n{', '<legend style={{')
content = content.replace('<p style={\n{', '<p style={{')
content = content.replace('<label style={\n{', '<label style={{')
content = content.replace('<button style={\n{', '<button style={{')
content = content.replace('<input style={\n{', '<input style={{')
content = content.replace('<textarea style={\n{', '<textarea style={{')
content = content.replace('<select style={\n{', '<select style={{')
content = content.replace('<fieldset style={\n{', '<fieldset style={{')
content = content.replace('<legend style={\n{', '<legend style={{')
content = content.replace('<p style={\n{', '<p style={{')
content = content.replace('<label style={\n{', '<label style={{')
content = content.replace('<button style={\n{', '<button style={{')
content = content.replace('<input style={\n{', '<input style={{')
content = content.replace('<textarea style={\n{', '<textarea style={{')
content = content.replace('<select style={\n{', '<select style={{')
content = content.replace('<fieldset style={\n{', '<fieldset style={{')
content = content.replace('<legend style={\n{', '<legend style={{')
content = content.replace('<p style={\n{', '<p style={{')
content = content.replace('<label style={\n{', '<label style={{')
content = content.replace('<button style={\n{', '<button style={{')
content = content.replace('<input style={\n{', '<input style={{')
content = content.replace('<textarea style={\n{', '<textarea style={{')
content = content.replace('<select style={\n{', '<select style={{')
content = content.replace('<fieldset style={\n{', '<fieldset style={{')
content = content.replace('<legend style={\n{', '<legend style={{')
content = content.replace('<p style={\n{', '<p style={{')
content = content.replace('}\n}', '}}')
content = content.replace('}\n}', '}}')
content = content.replace('}\n}\n>', '}}>')
content = content.replace('}\n}\n)', '}})')
content = content.replace('}\n}\n}\n>', '}}}>')

with open("C:/Users/Sebastian Lopez/Desktop/MULTIFACTU-Supabase/client/src/pages/TemplatesEditor.tsx", "w", encoding="utf-8") as f:
    f.write(content)

print("Fixed")